add: units tests with dl open and Makefile modified, github actions now check units tests

diff --git a/.github/workflows/asm.yml b/.github/workflows/asm.yml
--- a/.github/workflows/asm.yml
+++ b/.github/workflows/asm.yml
@@ -31,3 +31,23 @@ jobs:
         else
           echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
         fi
+
+    - name: check unit_tests
+      run: |
+          echo "## 🧪 Test results" >> $GITHUB_STEP_SUMMARY
+          {
+            set +e
+            make unit_tests ADDITIONAL_FLAGS="-Werror"
+            if [ $? -ne 0 ]; then
+              echo "- ### Test compilation failed ❌" >> $GITHUB_STEP_SUMMARY
+              echo "Test compilation failed."
+              exit 1
+            else
+              ./unit_tests
+              echo "| Passed ✅ | Failed ❌ | Assertions 🔬 |" >> $GITHUB_STEP_SUMMARY
+              echo "| :-------- | :-------- | :------------ |" >> $GITHUB_STEP_SUMMARY
+              ./unit_tests --color=never 2>&1 | grep "===] Synthesis: Tested: " \
+                | awk '{print "|" $7, "|" $10, "|" $4}' >> $GITHUB_STEP_SUMMARY
+              exit 0
+            fi
+          }
